volumes:
  postgres-data:


services:
  reactapp:
    build: ./front
    tty: true
    working_dir: /app
    volumes:
      - ./front:/app
    command: sh -c "npm start"
    ports:
      - "3000:3000"
    networks:
      - net_test
    env_file:
      - .env
  goapp:
    build: ./backend
    volumes:
      - ./backend:/app
    # command: sleep infinity
    command: air
    # network_mode: service:db
    depends_on:
      - db
      - redis
    ports:
      - "8080:8080"
    networks:
      - net_test
    env_file:
      - .env
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - net_test
    ports:
      - "5432:5432"
    env_file:
      - .env
  redis:
    container_name: redis
    image: redis:latest
    networks:
      - net_test
    ports:
      - 6379:6379
networks:
  net_test:
    external: true
